server:
  port: 80
  servlet:
    context-path: /spring-flyway

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/spring_flyway_db
    username: ${POSTGRES_DB_USER:admin}
    password: ${POSTGRES_DB_PASSWORD:masterkey}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: create
    generate-ddl: true
